/*
 * Copyright 2020 Gepardec IT Services GmbH and the CheetUnit contributors
 * SPDX-License-Identifier: Apache-2.0
 */

SET search_path = "cheetunit";
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-1, 'Albus', 'Dumbledore');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-2, 'Severus', 'Snape');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-3, 'Minerva', 'McGonagall');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-4, 'Harry', 'Potter');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-5, 'Ron', 'Weasley');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (-6, 'Hermione', 'Granger');

INSERT INTO COURSE(ID, NAME, YEAR, TEACHER_ID) VALUES (-1, 'Transfiguration', 1991, -3);
INSERT INTO COURSE(ID, NAME, YEAR, TEACHER_ID) VALUES (-2, 'Potions', 1991, -2);

INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-4, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-5, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-6, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-4, -2);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-5, -2);