/*
 * Copyright 2020 Gepardec IT Services GmbH and the CheetUnit contributors
 * SPDX-License-Identifier: Apache-2.0
 */

SET search_path = "cheetunit";
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-1, 'Albus', 'Dumbledore', '1881-08-01');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-2, 'Severus', 'Snape', '1960-01-09');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-3, 'Minerva', 'McGonagall', '1889-10-04');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-4, 'Harry', 'Potter', '1980-07-31');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-5, 'Ron', 'Weasley', '1980-03-01');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES (-6, 'Hermione', 'Granger', '1979-09-19');

INSERT INTO COURSE(ID, NAME, YEAR, TEACHER_ID) VALUES (-1, 'Transfiguration', 1991, -3);
INSERT INTO COURSE(ID, NAME, YEAR, TEACHER_ID) VALUES (-2, 'Potions', 1991, -2);

INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-4, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-5, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-6, -1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-4, -2);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (-5, -2);