#
# Copyright 2020 Gepardec IT Services GmbH and the CheetUnit contributors
# SPDX-License-Identifier: Apache-2.0
#

name: CI Pipeline

on:
  push:
    branches: [ feature/docker-cache-test ]
  pull_request:
    branches: [ feature/docker-cache-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B clean install -DskipITs=true -DskipUnitTests=false
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: cheetunit-jboss
        push_image_and_stages: false
    - name: Pre Integration Test
      run: |
        echo "=> Create network"
        docker network create cheetunit
        echo "=> Start database"
        docker run -d -p 5432:5432 --net=cheetunit \
          -e POSTGRES_DB=cheetunit \
          -e POSTGRES_USER=cheetunit \
          -e POSTGRES_PASSWORD=cheetunit \
          --name postgres postgres:12.5
        echo "=> Migrate database"
        cd ./cheetunit-examples/college-example/
        mvn flyway:migrate
        cd ../..
        echo "=> Start JBoss"
        docker run -d -p 8080:8080 --net=cheetunit --name cheetunit-jboss cheetunit-jboss
    - name: Integration Test
      run: mvn verify -DskipITs=false -DskipUnitTests=true
    - name: Post Integration Test
      run: |
        echo "=> Remove containers and network"
        docker rm -f cheetunit-jboss
        docker rm -f postgres
        docker network rm cheetunit
        docker image rm cheetunit-jboss
